# example netlify.toml
[build]
  command = "npm run build"
  functions = "functions"
  publish = "./src"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Link = "</assets/starfire.css>; rel=prefetch"

